### ISSUE TITLE
Missing Synchronous Lock() function

### ISSUE THREAD

**Issue by JesseKPhillips** [neosmart/AsyncLock#6]
Within the changes: https://github.com/neosmart/AsyncLock/compare/0.3.0.2...3.0.0

The Method for AsyncLock.Lock() was removed. Is this no longer supported, how does it get utilized outside a async function?

**Comment by mqudsi** [comment]
Hi @JesseKPhillips 

That was an oversight in the rewrite. A test should be written to verify the functionality and to make sure it doesn't happen in the future, but I've pushed an update (b39f19ca2835c6e1884d6a055765cef37aa9479a) that re-adds synchronous locking support (of course make sure to never call it in an async caller tree for fear of deadlock).

Can you give it a try?

**Comment by JesseKPhillips** [comment]
I'm setup to utilize published nuget packages. If a beta is published I could test it on my code tomorrow.

**Comment by mangotang** [comment]
If you will publish the fix to nuget I can also test it. :(

**Comment by JesseKPhillips** [comment]
Beta builds can be published and are opt-in, so it is a good way to distribute some testing.

**Comment by mqudsi** [comment]
Is publishing as beta just a matter of the name one chooses for the release or is there a separate flag for it?

**Comment by JesseKPhillips** [comment]
You use semantic version: 3.0.3-beta

This would be upgraded to 3.0.3 when that version is released.

**Comment by mqudsi** [comment]
@JesseKPhillips  thanks.

@all I've just published `3.1.0-BETA1` to nuget, with support for intermixing `.Lock()` and `.LockAsync()` calls (so long as `.Lock()` is never used in an awaited async call stack and all `.LockAsync()` calls are awaited). 

I apologize for the delay it's taken to push this to nuget: I had a nagging feeling that there was something off with the solution and found a test case that I could get to reliably trigger a race. This has been fixed in the published beta release.

Please feel free to kick this release around a bit and see what happens. If anyone wants to contribute more tests (failing or otherwise) that try out something not covered by the current unit tests, you are absolutely encouraged to do so.

I'd appreciate if everyone involved in this thread could let me know how this release works for them. Getting two completely separate synchronous and asynchronous locking branches to work nicely together was one of the ugliest bits of C# async code I've had the misfortune of dealing with and so feedback is heavily encouraged and can only benefit everyone.

**Comment by mqudsi** [comment]
@mangotang were you able to test the beta release?

**Comment by JesseKPhillips** [comment]
@mqudsi, Sorry for the day on trying this. I have pushed it into my test suite (where I utilize the library) and had success with it.

* I am utilizing the Synchronous approach (no async)
* The test suite reduces the need to for locking, so it isn't as stressful as some of my other suites.
* I only sent it through a single pass just now

I'm good for a release and will file issues which come up.

**Comment by mqudsi** [comment]
Thanks for the feedback, @JesseKPhillips. I'll hold off for a few more days before pushing a release. Wish I knew where to ask for more testers, I know there are thousands of users!

**Comment by mqudsi** [comment]
AsyncLock 3.1.0 pushed to nuget as a final release with the fixes for this issue.
